version: '3'
services:
  facebook:
    container_name: matrix-mautrix-facebook
    image: "{{ matrix_mautrix_facebook_docker_image }}"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    links:
      - facebook_db
    depends_on:
      - facebook_db
    cap_drop:
      - ALL
    restart: always
    networks:
      - external_network
    command: "python3 -m mautrix_facebook -c /config/config.yaml"      
    volumes:
      - "{{ matrix_mautrix_facebook_config_path }}:/config:z"
      - "{{ matrix_mautrix_facebook_data_path }}:/data:z"

  facebook_db:
    container_name: matrix-mautrix-facebook-db
    image: "{{ matrix_mautrix_facebook_docker_image }}"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    cap_drop:
      - ALL
    restart: "no"
    networks:
      - external_network
    command: "alembic -x config=/config/config.yaml upgrade head"
    volumes:
      - "{{ matrix_mautrix_facebook_config_path }}:/config:z"
      - "{{ matrix_mautrix_facebook_data_path }}:/data:z"

networks:
  external_network:
    external:
      name: nginx_nginx
