version: '3'
services:
  riot:
    hostname: riot.technodro.me
    container_name: matrix-riot-web
    image: "{{ matrix_riot_web_docker_image }}"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    cap_drop:
      - ALL
    restart: always
    read_only: true
    tmpfs: /tmp
    networks:
      - external_network
    volumes:
      - "{{ matrix_riot_web_data_path }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/dev/null:/etc/nginx/conf.d/default.conf:ro"
      - "{{ matrix_riot_web_data_path }}/config.json:/etc/riot-web/config.json:ro"
      {% if matrix_riot_web_embedded_pages_home_path is not none %}
      - "{{ matrix_riot_web_data_path }}/home.html:/etc/riot-web/home.html:ro"
      {% endif %}
      - "{{ matrix_riot_web_data_path }}/welcome.html:/etc/riot-web/welcome.html:ro"
#    ports:
#      {% if matrix_riot_web_container_http_host_bind_port %}
#      - "{{ matrix_riot_web_container_http_host_bind_port }}:8080"
#      {% endif %}
    environment:
      - VIRTUAL_HOST=riot.technodro.me
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=riot.technodro.me
      - LETSENCRYPT_EMAIL=admin@technodro.me
      - LETSENCRYPT_TEST=false
      - HSTS=off

networks:
  external_network:
    external:
      name: nginx_nginx
