version: '3'
services:
  postgres:
    container_name: matrix-postgres
    hostname: matrix-postgres
    image: "{{ matrix_postgres_docker_image_to_use }}"
    env_file: "{{ matrix_postgres_base_path }}/env-postgres-server"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    cap_drop:
      - ALL
    restart: always
    tmpfs:
      - /tmp
      - /run/postgresql
    networks:
      - external_network
    volumes:
      - {{ matrix_postgres_data_path }}:/var/lib/postgresql/data:rw
      - /etc/passwd:/etc/passwd:ro

networks:
  external_network:
    external:
      name: nginx_nginx
