version: '3'
services:
  postgres:
    container_name: matrix-postgres
    image: "{{ matrix_postgres_docker_image_to_use }}"
    env_file: "{{ matrix_postgres_base_path }}/env-postgres-server"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    cap_drop:
      - ALL
    restart: always
    tmpfs:
			- /tmp
			- /run/postgresql
    networks:
      - external_network
    volumes:
			-v {{ matrix_postgres_data_path }}:/var/lib/postgresql/data:rw \
			-v /etc/passwd:/etc/passwd:ro \
    ports:
      {% if matrix_postgres_container_postgres_bind_port %}
			- "{{ matrix_postgres_container_postgres_bind_port }}:5432"
			{% endif %}

networks:
  external_network:
    external:
      name: nginx_nginx
