version: '3'
services:
  irc:
    container_name: matrix-appservice-irc
    hostname: matrix-appservice-irc
    image: "{{ matrix_appservice_irc_docker_image }}"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    cap_drop:
      - ALL
    restart: always
    networks:
      - external_network
    command: "-c /config/config.yaml -f /config/registration.yaml -p 9999"
    volumes:
      - "{{ matrix_appservice_irc_config_path }}:/config:z"
      - "{{ matrix_appservice_irc_data_path }}:/data:z"
#ports:
#    {% if matrix_appservice_irc_container_http_host_bind_port %}
      #- "{{ matrix_appservice_irc_container_http_host_bind_port }}:9999"
#    {% endif %}

networks:
  external_network:
    external:
      name: nginx_nginx
