version: '3'
services:
  discord:
    container_name: matrix-appservice-discord
    hostname: matrix-appservice-discord
    image: "{{ matrix_appservice_discord_docker_image }}"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    cap_drop:
      - ALL
    restart: always
    networks:
      - external_network
    command: "node /build/src/discordas.js -p 9005 -c /cfg/config.yaml -f /cfg/registration.yaml"
    volumes:
      - "{{ matrix_appservice_discord_config_path }}:/cfg"
      - "{{ matrix_appservice_discord_data_path }}:/data"

networks:
  external_network:
    external:
      name: nginx_nginx