version: '3'
services:
  coturn:
    container_name: matrix-coturn
    hostname: matrix-coturn
    image: "{{ matrix_coturn_docker_image }}"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    entrypoint: turnserver
    read_only: true
    tmpfs: /var/tmp
    cap_drop:
      - ALL
    restart: always
    networks:
      - external_network
    command: -c /turnserver.conf
    volumes:
      - "{{ matrix_coturn_config_path }}:/turnserver.conf:ro"
      - "/var/lib/docker/lab/apps/nginx/certs/matrix.technodro.me/fullchain.pem:/data/matrix/ssl/config/live/matrix.technodro.me/fullchain.pem:ro"
      - "/var/lib/docker/lab/apps/nginx/certs/matrix.technodro.me/key.pem:/data/matrix/ssl/config/live/matrix.technodro.me/privkey.pem:ro"

    ports:
      - 3478:3478
      - 3478:3478/udp
      - 5349:5349
      - 5349:5349/udp
      - {{ matrix_coturn_turn_udp_min_port }}-{{ matrix_coturn_turn_udp_max_port }}:{{ matrix_coturn_turn_udp_min_port }}-{{ matrix_coturn_turn_udp_max_port }}/udp

networks:
  external_network:
    external:
      name: nginx_nginx
