version: '3'
services:
  main:
    container_name: matrix-synapse
    hostname: matrix.technodro.me
    image: "{{ matrix_synapse_docker_image }}"
    user: "{{ matrix_user_uid }}:{{ matrix_user_gid }}"
    cap_drop:
      - ALL
    restart: always
    read_only: true
    networks:
      - external_network
    entrypoint: python
    command: "-m synapse.app.homeserver -c /data/homeserver.yaml"
    tmpfs:
      - /tmp
    volumes:
      - "{{ matrix_synapse_config_dir_path }}:/data:ro"
      - "{{ matrix_synapse_run_path }}:/matrix-run:rw"
      - "{{ matrix_synapse_storage_path }}:/matrix-media-store-parent:slave"
      - "{{ matrix_appservice_irc_config_path }}/registration.yaml:/matrix-appservice-irc-registration.yaml:ro"
      - "{{ matrix_mautrix_facebook_config_path }}/registration.yaml:/matrix-mautrix-facebook-registration.yaml:ro"
      - "{{ matrix_mautrix_telegram_config_path }}/registration.yaml:/matrix-mautrix-telegram-registration.yaml:ro"
      - "{{ matrix_mautrix_whatsapp_config_path }}/registration.yaml:/matrix-mautrix-whatsapp-registration.yaml:ro"
      - "{{ matrix_appservice_discord_config_path }}/registration.yaml:/matrix-appservice-discord-registration.yaml:ro"
      - "/var/lib/docker/lab/apps/nginx/certs/matrix.technodro.me/:/certs/:ro"
      #- "{{ matrix_synapse_ext_path }}/synapse-simple-antispam/synapse_simple_antispam:{{ matrix_synapse_in_container_python_packages_path }}/synapse_simple_antispam,ro"

    environment:
      - "SYNAPSE_CACHE_FACTOR={{ matrix_synapse_cache_factor }}"
      - VIRTUAL_HOST=matrix.technodro.me
      - VIRTUAL_PORT=8008
      - LETSENCRYPT_HOST=matrix.technodro.me
      - LETSENCRYPT_EMAIL=admin@technodro.me
      - LETSENCRYPT_TEST=false
      - HSTS=off
    ports:
      - "8448:8448"
networks:
  external_network:
    external:
      name: nginx_nginx
